name: Generate ASCII Artwork
on:
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
      
      - name: Excute Cowsay CMD
        run: cowsay -f dragon "run for cover, i am a Dragon"
